# trapyz geo loc config

version = "1.0"
# default radius 300 meters 
radius = "300"
nworkers = 4
tpz_env = "dev"
#cache type can be "inmem" or "redis"
cache_type= "redis"
[db]
    [db.mysql-prod]
    server = ""
    port = "3306"
    dbname = ""
    user = ""
    password = ""

    [db.redis-prod]
    server = ""
    port = "6379"
    dbname = ""
    user = ""
    password = ""

    [db.mysql-dev]
    server = "127.0.0.1"
    port = "3301"
    dbname = "trapyz_beta"
    user = "root"
    password = "admin"

    [db.redis-dev]
    server = "127.0.0.1"
    port = "6379"
    dbname = ""
    user = ""
    password = ""

#Options for S3 NOTE: Do not store AWS credentials here
[aws]
    [aws.s3-prod]
    profile="trapyz"
    bucket = "usergeologs"
    prefixes=[
        "usergeopointlocation",
        "userwificonnectedlocation",
        "userwifiscanlocation",
        "usergeopixellogs"
    ]
    s3dump_prefix = "~/s3dump"

    [aws.s3-dev]
    profile="trapyz-dev"
    bucket = "usergeologsb"
    prefixes=["usergeopixellogs"]
    s3dump_prefix = "~/s3dump-dev"

[output]
directory = "./tpz-geo-out"
file = "geocalc.out"
logdir  = "./tpz-geo-out"
logfile = "geocalc-process.log"
