# trapyz geo loc config

version = "1.0"
# default radius 300 meters 
radius = "300"
nworkers = 4
tpz_env = "dev"
#cache type can be "inmem" or "redis"
cache_type= "redis"
[db]
    [db.mysql-prod]
    server = ""
    port = "3306"
    dbname = ""
    user = ""
    password = ""

    [db.redis-prod]
    server = ""
    port = "6379"
    dbname = ""
    user = ""
    password = ""

    [db.mysql-dev]
    server = "127.0.0.1"
    port = "3301"
    dbname = "trapyz_beta"
    user = "root"
    password = "admin"

    [db.redis-dev]
    server = "127.0.0.1"
    port = "6379"
    dbname = ""
    user = ""
    password = ""

#Options for S3 NOTE: Do not store AWS credentials here
[aws]
    [aws.s3-prod]
    region="us-east-1"
    profile="trapyz"
    bucket = "usergeologs"
    prefixes=[
        "usergeopointlocation",
        "userwificonnectedlocation",
        "userwifiscanlocation",
        "usergeopixellogs"
    ]
    #date from and To are optional DateFrom defaults to yesterday Midnight
    #date To defaults to today. Dates have to be in YYYY/MM/DD/[HH] format
    #HH stands for hour of the day, valid values are from 00-23, HH is optional 
    date_from=""
    date_to=""
    #Directory prefix, suffix will be tpz env [eg:s3dump-prod] 
    s3dump_prefix = "./s3dump"
    flatten = true
    unzip = true

    [aws.s3-dev]
    region="us-east-1"
    profile="bobble"
    bucket = "usergeologs"
    prefixes=["usergeopixellogs"]
    #Directory prefix, suffix will be tpz env  [eg: s3dump-dev]
    date_from= "2018/09/06/01"
    date_to=   "2018/09/06/02"
    s3dump_prefix = "./s3dump"
    flatten = true
    unzip = true

[output]
directory = "./tpz-geo-out"
file = "geocalc.out"
logdir  = "./tpz-geo-out"
logfile = "geocalc-process.log"
