# trapyz geo loc config

version = "1.0"
# default radius 300 meters 
radius = 300

[databases]
# TOML does not care about tabs/indents
    [mysqldb.prod]
    server = "172.31.0.193"
    port = "3306"
    dbname = "trapyz_beta"
    user = "ciscoplanet"
    password = "pwx"

    [redis.prod]
    server = "172.31.28.193"
    port = "6379"

[output]
directory = "./tpz-geocalc"
file = "geocalc.out"
logdir  = "./tpz-geocalc"
logfile = "geocalc-process.log"

